#' Create Africa Uniform Cartogram Heatmaps
#'
#' The cartogram heatmaps generated by the included methods
#' are an alternative to choropleth maps for African countries
#' and are based on work by the creators of the "statebins" package.
#' "africabins" preserve as much of the geographic placement of the countries as
#' possible but have the look and feel of a traditional heatmap. Functions are
#' provided that allow for use of a binned, discrete scale, a continuous scale
#' or manually specified colors depending on what is needed for the underlying data.
#'
#' @md
#' @name africabins-package
#' @docType package
#' @author Bob Rudis (bob@@rud.is)
#' @importFrom grid unit
#' @importFrom scales alpha
#' @importFrom ggplot2 ggplot geom_tile scale_fill_manual guides geom_tile ggplotGrob
#' @importFrom ggplot2 geom_point geom_text scale_color_manual guides theme labs
#' @importFrom ggplot2 scale_x_continuous scale_y_continuous coord_equal theme_bw
#' @importFrom ggplot2 aes element_rect element_blank element_text resolution
#' @importFrom ggplot2 aes_string aes_ scale_y_reverse layer GeomRect margin %+replace%
#' @importFrom ggplot2 scale_fill_brewer ggtitle rel ggproto draw_key_polygon Geom Stat
NULL
